### ISSUE TITLE
BMI calculated as 0.00XXXX

### ISSUE THREAD

**Issue by licaon-kter** [shoukolate/CalorieScope#1]
...but info is as XX.X 

I guess you need to multiply by 10000 here https://github.com/shoukolate/CalorieScope/blob/master/app/src/main/java/org/dynamicsoft/caloriescope/activities/CalculatorActivity.java#L190

**Comment by likeadragonmaid** [comment]
Strange, it's working fine here. Please upload a screenshot or screen recording so that I can try to reproduce it.

**Comment by licaon-kter** [comment]
![org dynamicsoft caloriescope_1](https://user-images.githubusercontent.com/2282799/74929138-d16c6180-53d2-11ea-91a2-59f97133a378.jpg)

**Comment by likeadragonmaid** [comment]
You are entering height (meters) as 175 which is too long for being a human's height. If you are entering 175 as centimeters, you should convert it to meters and enter it as 1.75.
Also with latest commit I made it easier to calculate since you will need to enter height as feet and inches. So if your height is 175 cm (1.75 meters), you should enter it in feet and inches i.e. 5.74 (Feet.Inch).

**Comment by licaon-kter** [comment]
Indeed, my bad, thought it's `cm`

Anyway, I hope you respect my Android locale setting and show kg/cm and not that system used only by 1 country in the whole world. ;)
